# Data analitika üçün Pandas kitabxanası
## Akademik səviyyəli ev tapşırığı

**Məqsəd:** Bu notebook `pandas` kitabxanasının təməl məlumat manipulyasiyası (data manipulation) funksiyalarından başlayaraq mürəkkəb aqreqasiya, birləşdirmə və pivot cədvəllərinə qədər olan imkanlarını öyrənmək üçün 50 sistemli tapşırıqdan ibarətdir. Tapşırıqlar real dünya datalarını simulyasiya edir.

### Bölmə 1: Pandas-a Giriş və Veri Strukturları (Data Structures)

In [2]:
# 1. Pandas kitabxanasını 'pd' olaraq import edin və versiyasını çap edin.
import pandas as pd
pd.__version__

'2.3.3'

In [3]:
# 2. [10, 20, 30, 40, 50] siyahısından (list) ibarət bir Pandas Series (Təkölçülü vektor) yaradın.
pd.Series(data=[10, 20, 30, 40, 50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# 3. {'a': 1, 'b': 2, 'c': 3, 'd': 4} lüğətindən (dictionary) xüsusi indeksli Pandas Series yaradın.
pd.Series(data={"a":1, "b":2, "c":3, "d":4})

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
# 4. {'Ad': ['Əli', 'Vəli', 'Aysel'], 'Yaş': [25, 30, 22]} lüğətindən iki sütunlu DataFrame yaradın.
pd.DataFrame(data={'Ad': ['Əli', 'Vəli', 'Aysel'], 'Yaş': [25, 30, 22]})

      Ad  Yaş
0    Əli   25
1   Vəli   30
2  Aysel   22

In [7]:
# 5. Siyahıların siyahısından (list of lists) DataFrame yaradın və həm sütun, həm də sətir (index) adlarını təyin edin.
pd.DataFrame(
    data=[
        ["Vugar", 24, "Data Scientist", 2500],
        ["Ilgar", 24, "Process Engineer", 3500],
        ["Ravan", 23, "Production Engineer", 3000],
        ["Rauf", 22, "Finance Analyst", 2800]],
    index=[1001, 1002, 1003, 1004],
    columns=["name", "age", "role", "salary"])

       name  age                 role  salary
1001  Vugar   24       Data Scientist    2500
1002  Ilgar   24     Process Engineer    3500
1003  Ravan   23  Production Engineer    3000
1004   Rauf   22      Finance Analyst    2800

### Bölmə 2: Məlumatın Yüklənməsi və İlkin Baxış (Data Ingestion)
Bu bölmədən etibarən məşhur **Titanic** məlumat dəstindən istifadə edəcəyik.

In [58]:
# 6. Aşağıdakı URL-dən Titanic məlumat dəstini oxuyun və 'df' dəyişəninə mənimsədin.
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
# 7. Məlumat dəstinin strukturunu anlamaq üçün ilk 10 sətri ekrana çıxarın.
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [10]:
# 8. Məlumat dəstinin son 5 sətrini ekrana çıxarın.
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [11]:
# 9. DataFrame-in neçə sətir və sütundan ibarət olduğunu (shape atributu) göstərin.
df.shape

(891, 12)

In [12]:
# 10. Məlumat dəstinin sütun tiplərini, boş olmayan dəyər sayını və yaddaş istifadəsini göstərən ümumi xülasəni (info) çıxarın.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
# 11. Yalnız ədədi (numeric) sütunların mərkəzi meyl (mean, median) və yayılma (std, min, max) statistikalarını (describe) göstərin.
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Bölmə 3: Məlumatın Seçilməsi, İndeksləmə və Filtrlənməsi (Data Selection & Filtering)

In [15]:
# 12. Yalnız 'Name' (Ad) sütununu tək bir Series obyekti kimi seçin və ilk 5 dəyəri göstərin.
df["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [16]:
# 13. 'Name' və 'Age' (Yaş) sütunlarını birlikdə, DataFrame formatında seçin.
df[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [17]:
# 14. Yaşı 30-dan böyük olan sərnişinləri filtrləyərək yeni bir DataFrame yaradın.
mask = df["Age"] > 30
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
# 15. Məntiqi operatorlardan (&) istifadə edərək yaşı 30-dan böyük olan VƏ qadın ('female') sərnişinləri filtrləyin.
mask = (df["Age"] > 30) & (df["Sex"] == "female")
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [19]:
# 16. Məntiqi operatorlardan (|) istifadə edərək yaşı 18-dən kiçik olan VƏ YA 1-ci sinif (Pclass == 1) səyahət edənləri tapın.
mask = (df["Age"] < 18) | (df["Pclass"] == 1)
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [20]:
# 17. `loc` metodundan istifadə edərək indeks nömrəsi 10-dan 20-yə qədər (20 daxil) olan sətirləri və yalnız 'Name', 'Age' sütunlarını seçin.
df.loc[10:20, ["Name", "Age"]]

                                                 Name   Age
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
12                     Saundercock, Mr. William Henry  20.0
13                        Andersson, Mr. Anders Johan  39.0
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
16                               Rice, Master. Eugene   2.0
17                       Williams, Mr. Charles Eugene   NaN
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
19                            Masselmani, Mrs. Fatima   NaN
20                               Fynney, Mr. Joseph J  35.0

In [21]:
# 18. `iloc` metodundan istifadə edərək ilk 5 sətri və ilk 3 sütunu rəqəmsal mövqelərinə görə seçin.
df.iloc[:5, :3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [26]:
# 19. Sərnişinlərin bilet qiyməti (Fare) 100-dən çox olanların ümumi sayını tapın.
mask = df["Fare"] > 100
len(df[mask])

53

In [27]:
# 20. 'Embarked' (Liman) sütunu 'C' və ya 'S' olan sətirləri `.isin()` metodu ilə filtrləyin.
mask = df["Embarked"].isin(["C", "S"])
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### Bölmə 4: Məlumatın Təmizlənməsi və Transformasiyası (Data Cleaning & Transformation)

In [59]:
# 21. Hər bir sütunda neçə ədəd çatışmayan (NaN) dəyər olduğunu hesablayın.
df.isna().sum(axis=0)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [43]:
# 22. İçərisində heç olmasa bir dənə çatışmayan dəyər olan bütün sətirləri (dropna) müvəqqəti silin və qalan sətir sayını göstərin.
df.dropna(axis=0, how="any", inplace=False).shape[0]

183

In [46]:
# 23. 'Cabin' sütununda 70%-dən çox məlumat çatışmadığı üçün bu sütunu df-dən tamamilə silin (drop).
df["Cabin"].value_counts(normalize=True, dropna=False)[:5]

Cabin
NaN            0.771044
C23 C25 C27    0.004489
G6             0.004489
B96 B98        0.004489
C22 C26        0.003367
Name: proportion, dtype: float64

In [60]:
df.drop(columns="Cabin", inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [62]:
# 24. 'Age' sütunundakı boş dəyərləri (NaN) bütün sərnişinlərin median yaşı ilə əvəzləyin (fillna).
df["Age"].value_counts(dropna=False)

Age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [64]:
median_age = df["Age"].median()
df.fillna({"Age":median_age}, inplace=True)
df["Age"].value_counts(dropna=False)

Age
28.00    202
24.00     30
22.00     27
18.00     26
19.00     25
        ...
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: count, Length: 88, dtype: int64

In [68]:
# 25. 'Embarked' sütunundakı boş dəyərləri ən çox təkrar olunan dəyər (mode) ilə doldurun.
df["Embarked"].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [73]:
mode_embarked = df["Embarked"].mode()[0]
df.fillna({"Embarked":mode_embarked}, inplace=True)
df["Embarked"].value_counts(dropna=False)

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [81]:
# 26. Məlumat dəstində təkrarlanan sətirlərin (duplicates) olub-olmadığını yoxlayın və varsa silin.
df.duplicated().sum()

np.int64(0)

In [83]:
# 27. Sütun adlarında aydınlıq yaratmaq üçün 'Pclass' sütununun adını 'Passenger_Class' olaraq dəyişdirin (rename).
df.rename(columns={"Pclass":"Passenger_Class"}, inplace=True)
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [87]:
# 28. 'Sex' sütunundakı 'male' və 'female' kateqoriyalarını riyazi analiz üçün müvafiq olaraq 0 və 1 rəqəmləri ilə əvəzləyin (map/replace).
df.replace({"Sex":{"male":0, "female":1}}, inplace=True)
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,Q

In [88]:
# 29. Ailə ölçüsünü göstərən yeni bir 'Family_Size' sütunu yaradın ('SibSp' və 'Parch' sütunlarının cəmi + 1).
df["Family_Size"] = df["SibSp"] + df["Parch"] + 1
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.4500,S,4
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,Q,1

In [90]:
# 30. 'Fare' sütununun veri tipini float64-dən int32-yə (tam ədəd) çevirin (astype).
df["Fare"] = df["Fare"].astype(dtype="int32")
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23,S,4
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1

### Bölmə 5: Qruplaşdırma və Aqreqasiya (GroupBy & Aggregation)

In [101]:
# 31. Sərnişin sinfinə ('Passenger_Class') görə qruplaşdırıb (groupby), hər sinfin orta bilet qiymətini tapın.
df.groupby(by="Passenger_Class").aggregate(avg_fare=("Fare", "mean"))

                  avg_fare
Passenger_Class
1                83.745370
2                20.456522
3                13.173116

In [113]:
# 32. Cinsiyyətə görə sağ qalma ('Survived') dərəcəsini (orta dəyərini) faiz ifadəsi ilə hesablayın.
df.groupby(by="Sex").aggregate({"Survived":"mean"}) * 100

      Survived
Sex
0    18.890815
1    74.203822

In [105]:
# 33. Çoxölçülü qruplaşdırma: Həm 'Passenger_Class', həm də cinsiyyətə görə qruplaşdırıb 'Age' sütununun medianını tapın.
df.groupby(by=["Passenger_Class", "Sex"]).aggregate(median_age=("Age", "median"))

                     median_age
Passenger_Class Sex
1               0          36.0
                1          32.5
2               0          29.0
                1          28.0
3               0          28.0
                1          28.0

In [111]:
# 34. `.agg()` metodundan istifadə edərək 'Fare' sütununun həm minimum, həm maksimum, həm də orta dəyərini tək bir cədvəldə göstərin.
df["Fare"].aggregate(["min", "mean", "median", "max"])

min         0.000000
mean       31.785634
median     14.000000
max       512.000000
Name: Fare, dtype: float64

In [114]:
# 35. 'Embarked' sütunundakı kateqoriyaların tezliyini (hansı limandan neçə sərnişin minib) hesablayın (value_counts).
df["Embarked"].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [123]:
# 36. Qruplaşdırma vasitəsilə ən çox bilet ödənişi edən sərnişin(lər)in hansı sinifdə (Pclass) olduğunu təyin edin.
df.groupby(by="Passenger_Class").aggregate(Total_Fare=("Fare", "sum"), Passenger_Count=("Fare", "count"))

                 Total_Fare  Passenger_Count
Passenger_Class
1                     18089              216
2                      3764              184
3                      6468              491

### Bölmə 6: Sıralama və İndeks İdarəetməsi (Sorting & Indexing)

In [124]:
# 37. Məlumat dəstini 'Age' sütununa görə artan ardıcıllıqla sıralayın (sort_values).
df.sort_values(by="Age")

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
803,804,1,3,"Thomas, Master. Assad Alexander",0,0.42,0,1,2625,8,C,2
755,756,1,2,"Hamalainen, Master. Viljo",0,0.67,1,1,250649,14,S,3
644,645,1,3,"Baclini, Miss. Eugenie",1,0.75,2,1,2666,19,C,4
469,470,1,3,"Baclini, Miss. Helene Barbara",1,0.75,2,1,2666,19,C,4
831,832,1,2,"Richards, Master. George Sibley",0,0.83,1,1,29106,18,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,0,3,"Connors, Mr. Patrick",0,70.50,0,0,370369,7,Q,1
96,97,0,1,"Goldschmidt, Mr. George B",0,71.00,0,0,PC 17754,34,C,1
493,494,0,1,"Artagaveytia, Mr. Ramon",0,71.00,0,0,PC 17609,49,C,1
851,852,0,3,"Svensson, Mr. Johan",0,74.00,0,0,347060,7,S,1
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",0,80.00,0,0,27042,30,S,1

In [125]:
# 38. Məlumat dəstini əvvəlcə 'Passenger_Class' (artan), daha sonra 'Fare' (azalan) ardıcıllıqla sıralayın.
df.sort_values(by=["Passenger_Class", "Fare"], ascending=[True, False])

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
258,259,1,1,"Ward, Miss. Anna",1,35.0,0,0,PC 17755,512,C,1
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",0,36.0,0,1,PC 17755,512,C,2
737,738,1,1,"Lesurer, Mr. Gustave J",0,35.0,0,0,PC 17755,512,C,1
27,28,0,1,"Fortune, Mr. Charles Alexander",0,19.0,3,2,19950,263,S,6
88,89,1,1,"Fortune, Miss. Mabel Helen",1,23.0,3,2,19950,263,S,6
...,...,...,...,...,...,...,...,...,...,...,...,...
378,379,0,3,"Betros, Mr. Tannous",0,20.0,0,0,2648,4,C,1
179,180,0,3,"Leonard, Mr. Lionel",0,36.0,0,0,LINE,0,S,1
271,272,1,3,"Tornquist, Mr. William Henry",0,25.0,0,0,LINE,0,S,1
302,303,0,3,"Johnson, Mr. William Cahoone Jr",0,19.0,0,0,LINE,0,S,1
597,598,0,3,"Johnson, Mr. Alfred",0,49.0,0,0,LINE,0,S,1

In [133]:
# 39. DataFrame-in əsas indeksini 'PassengerId' sütunu olaraq təyin edin (set_index).
df.set_index(keys="PassengerId", inplace=True)
df

,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C,2
3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,S,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,S,2
5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13,S,1
888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30,S,1
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23,S,4
890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1
891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1

In [134]:
# 40. İndeksi sıfırlayın (reset_index) və köhnə indeksi məlumat kimi df-də saxlayın.
df.reset_index(drop=False, inplace=True)
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23,S,4
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1

### Bölmə 7: Məlumatların Birləşdirilməsi (Merge, Join, Concat)
Bu bölmə üçün xüsusi olaraq iki kiçik DataFrame yaradılmışdır. Aşağıdakı xananı işə salın və istifadə edin.

In [135]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Ad': ['Əli', 'Vəli', 'Aysel']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Maaş': [500, 600, 700]})

In [136]:
# 41. df1 və df2-ni sətir oxu üzrə alt-alta birləşdirin (concat, axis=0) və indeksləri yeniləyin (ignore_index=True).
pd.concat(objs=[df1, df2], axis=0, ignore_index=True)

   ID     Ad   Maaş
0   1    Əli    NaN
1   2   Vəli    NaN
2   3  Aysel    NaN
3   2    NaN  500.0
4   3    NaN  600.0
5   4    NaN  700.0

In [137]:
# 42. df1 və df2-ni sətir indekslərinə görə yan-yana birləşdirin (concat axis=1).
pd.concat(objs=[df1, df2], axis=1)

   ID     Ad  ID  Maaş
0   1    Əli   2   500
1   2   Vəli   3   600
2   3  Aysel   4   700

In [138]:
# 43. df1 və df2-ni ortaq 'ID' sütunu üzərindən Inner Join vasitəsilə birləşdirin (merge).
pd.merge(left=df1, right=df2, how="inner", on="ID")

   ID     Ad  Maaş
0   2   Vəli   500
1   3  Aysel   600

In [139]:
# 44. df1 və df2-ni df1-in bütün sətirləri saxlanılmaqla Left Join vasitəsilə birləşdirin.
pd.merge(left=df1, right=df2, how="left", on="ID")

   ID     Ad   Maaş
0   1    Əli    NaN
1   2   Vəli  500.0
2   3  Aysel  600.0

In [140]:
# 45. df1 və df2-ni heç bir məlumat itkisi olmadan (Outer Join) birləşdirin.
pd.merge(left=df1, right=df2, how="outer", on="ID")

   ID     Ad   Maaş
0   1    Əli    NaN
1   2   Vəli  500.0
2   3  Aysel  600.0
3   4    NaN  700.0

### Bölmə 8: Advanced Texnikalar (Pivot, Apply, String Manipulation)

In [141]:
# 46. Titanic məlumat dəstində sətirlərdə 'Sex', sütunlarda 'Passenger_Class' və içəridə 'Fare'-in orta qiymətini nümayiş etdirən Pivot Cədvəl (pivot_table) yaradın.
df.pivot_table(index="Sex", columns="Passenger_Class", values="Fare")

Passenger_Class           1          2          3
Sex
0                 66.836066  19.527778  12.167147
1                105.691489  21.776316  15.597222

In [142]:
# 47. 'Name' sütunundakı bütün mətnləri kiçik hərflərə (lowercase) çevirin (.str.lower).
df["Name"].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [145]:
# 48. Mətn analizi: 'Name' sütununda 'Mr.' titulu keçən sərnişinləri tapın (.str.contains).
mask = df["Name"].str.contains("Mr\.")
df[mask]

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1
5,6,0,3,"Moran, Mr. James",0,28.0,0,0,330877,8,Q,1
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,17463,51,S,1
12,13,0,3,"Saundercock, Mr. William Henry",0,20.0,0,0,A/5. 2151,8,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",0,33.0,0,0,349257,7,S,1
883,884,0,2,"Banfield, Mr. Frederick James",0,28.0,0,0,C.A./SOTON 34068,10,S,1
884,885,0,3,"Sutehall, Mr. Henry Jr",0,25.0,0,0,SOTON/OQ 392076,7,S,1
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1

In [149]:
# 49. `.apply()` metodundan istifadə edərək 'Age' sütunundakı hər bir dəyəri vizual onluqlara çevirin (məsələn, 25 yaşı 2-yə, yəni yaş / 10).
df["Age_Group"] = df["Age"].apply(func=lambda x: str(int(((x // 10) * 10))) + "s")  # I made some changes to the logic of the question :)
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2,20s
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C,2,30s
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,S,1,20s
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,S,2,30s
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1,30s
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13,S,1,20s
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30,S,1,10s
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23,S,4,20s
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1,20s
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1,30s

In [151]:
# 50. `lambda` funksiyası ilə mürəkkəb əməliyyat: 'Fare' dəyəri 50-dən böyükdürsə 'Premium', kiçikdirsə 'Standard' yazan yeni bir 'Ticket_Category' sütunu yaradın.
df["Ticket_Category"] = df["Fare"].apply(func=lambda x: "Premium" if x > 50 else "Standard")
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size,Age_Group,Ticket_Category
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,S,2,20s,Standard
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C,2,30s,Premium
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,S,1,20s,Standard
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,S,2,30s,Premium
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,S,1,30s,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13,S,1,20s,Standard
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30,S,1,10s,Standard
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23,S,4,20s,Standard
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30,C,1,20s,Standard
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7,Q,1,30s,Standard